### ISSUE TITLE
_this.props.action[i] is not function  how to pass data or variable inside that click methods ?

### ISSUE THREAD

**Issue by birjubhatt** [itsrajverma/react-native-option-menu#1]
const myIcon = (<Icon name="rocket" size={30} color="#900" />)
<OptionsMenu
  customButton={myIcon}
  destructiveIndex={1}
  options={["Edit", "Delete", "Cancel"]}
  actions={[editPost,deletePost]}/>

i use this in my  fileList.map((item, i) => ()
and how to pass this item in method if i press delete ?
whenever is wirhte  deletePost(item) that time i get 

![screenshot-2021-08-04_10 46 53 036](https://user-images.githubusercontent.com/21102131/128151460-a0d28597-b1bf-421b-85cb-5ee6d07e05f8.png)

**Comment by bhavinatharva** [comment]
> const myIcon = ()
> <OptionsMenu
> customButton={myIcon}
> destructiveIndex={1}
> options={["Edit", "Delete", "Cancel"]}
> actions={[editPost,deletePost]}/>
> 
> i use this in my fileList.map((item, i) => ()
> and how to pass this item in method if i press delete ?
> whenever is wirhte deletePost(item) that time i get
> 
> ![screenshot-2021-08-04_10 46 53 036](https://user-images.githubusercontent.com/21102131/128151460-a0d28597-b1bf-421b-85cb-5ee6d07e05f8.png)

You can use this way to add your functions 


```
doEdit = (id: number) => {
  };
  
  doDelete = (id: number) => {
  };
 <OptionsMenu
                button={assets.imgListMenu}
                buttonStyle={styles.imgMenu}
                destructiveIndex={1}
                options={["Edit", "Delete"]}
                actions={[
                  () => this.doEdit(item.id),
                  () => this.doDelete(item),
                ]}
              />
```
